name: CI
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setting up Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - run: make build
      - run: make test
