name: CD
on:
  push:
    branches:
      - "main"
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/javierlgroba/task-list/backend:latest
      - name: Login to the Docker registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to the Docker registry
        run: docker push ghcr.io/javierlgroba/task-list/backend:latest
